### PR TITLE
The `equalByValue` util function should compare GUIDs by value (close T698635)

### PR DESCRIPTION
**Pull request by churkin**

### CODE REVIEW

**Review by AlekseyMartynov — COMMENTED** [review]
Looks fine.
~~How do you plan to use this?~~
Ok, I see it's meant to resolve [T698227](https://devexpress.com/issue=T698227). But what is the exact issue with `callBase` and OData?

**Update:** Actually, T698227 is closed, and the branch name suggests it's about T698588. Confusion!

P.S. https://news.ycombinator.com/item?id=4744314 😈

**Review by DokaRus — COMMENTED** [review]
LGTM

**Comment by churkin** [comment]
@AlekseyMartynov Good note, I've missed the name of my local branch, but I'm sure that this is not a big problem :). The `GUID` is a inheritor of the `Class`, At the some point a new `callBase: undefined` field appears in it. Because of it our internal comparator can not compare two equal GUIDs. Can you suggest something other than `delete` using?

**Comment by AlekseyMartynov** [comment]
FYI we are currently considering an alternative solution to the initial ticket

**Review by vconst — CHANGES_REQUESTED** [review]
I think that fix should be in selection instead of basic class.
The delete operator in basic class may cause very big performance degradation. For example in array_query.

**Comment by churkin** [comment]
@vconst The best way is removing all unvalue inheritances

**Review by jsdmitry — DISMISSED** [review]

**Review by vconst — DISMISSED** [review]

**Review by DokaRus — DISMISSED** [review]

**Review by nightskylark — DISMISSED** [review]

**Review by AlekseyMartynov — DISMISSED** [review]
Subj needs updating

**Review by jsdmitry — DISMISSED** [review]

**Comment by churkin** [comment]
Ready to review

**Review by AlekseyMartynov — APPROVED** [review]

**Comment by churkin** [comment]
Do not be shy, guys.

**Review by nightskylark — APPROVED** [review]

**Pull request merged**
