### PR TITLE
Fix required message

### PR DESCRIPTION
**Pull request by pekkast**
required = pakollinen

### CODE REVIEW

**Comment by pekkast** [comment]
Any chance to get this reviewed?

**Comment by pekkast** [comment]
@babich-a Can't anyone else approve this request? It's very annoying that the message is fully incorrect.

**Comment by pekkast** [comment]
image
It says: 
name is optional
integration is optional
source_id is optional

**Review by BingoRUS — APPROVED** [review]
Hello @pekkast! I apologize for the late reply. I'm going to merge your pull request now. The updated localization file will be available in the following releases: v19.2.10, v20.1.8, v20.2.2 (beta).

Thank you for your patience and for helping us make our product better.

**Pull request merged**
