### PR TITLE
DataGrid/TreeList: Change 'editData' namings to 'change'

### PR DESCRIPTION
**Pull request by jtoming830**

### CODE REVIEW

**Review by vconst — COMMENTED** [review]
Empty changes fix commits exist in this PR.

**Comment by jtoming830** [comment]
> Empty changes fix commits exist in this PR.

Yes, because this branch was created from the HEAD of branch with empty changes fix. After merging I will rebase this branch and pull request will not contain these commits. This is also the reason of the WIP label on this pull request.

**Comment by NickMitrokhin** [comment]
Maybe it is better to rename all private methods such as **_beforeSaveEditData** to **_beforeSaveChanges**?

**Comment by jtoming830** [comment]
I thought about this - but these private methods are named consistently with public methods - **saveEditData** and **cancelEditData**. So I didn't rename methods, which are related to **saveEditData** and **cancelEditData** - **_saveEditDataInner**, **_cancelEditDataCore**, **_beforeSaveEditData**, etc.

**Comment by NickMitrokhin** [comment]
I see.

**Review by NickMitrokhin — APPROVED** [review]

**Review by vconst — APPROVED** [review]

**Pull request merged**
