### PR TITLE
Fix 'renderedCallback' behavior when creating nested templates during the execution of the callback (T758209)

### PR DESCRIPTION
**Pull request by DokaRus**

### CODE REVIEW

**Review by nightskylark — DISMISSED** [review]

**Comment by AlekseyMartynov** [comment]
Please hold on, don't merge yet.

**Comment by DokaRus** [comment]
> Please hold on, don't merge yet.

I'll be waiting for your approve

**Comment by AlekseyMartynov** [comment]
Please import this commit: https://github.com/AlekseyMartynov/DevExtreme/commit/d7970fa31b8ab7038aea409e8dcb21a1c586cad9

**Comment by AlekseyMartynov** [comment]
Also merge with the upstream to include https://github.com/DevExpress/DevExtreme/pull/8932

**Review by AlekseyMartynov — APPROVED** [review]

**Review by nightskylark — APPROVED** [review]

**Pull request merged**
