### PR TITLE
Provide es and pt translations for devextreme 18.2

### PR DESCRIPTION
**Pull request by pedrofurtado**
@BingoRUS 👍

### CODE REVIEW

**Review by BingoRUS — CHANGES_REQUESTED** [review]
Hi @pedrofurtado,

Can you please also fill missing messages for FileUploader?
We have 3 new strings:
dxFileUploader-invalidFileExtension
dxFileUploader-invalidMaxFileSize
dxFileUploader-invalidMinFileSize

**Comment by pedrofurtado** [comment]
@BingoRUS Ok. I update the translations of ES and pt 👍

**Comment by pedrofurtado** [comment]
Changes done ✅

**Review by BingoRUS — APPROVED** [review]
@pedrofurtado thanks again for your help!

**Pull request merged**
