### PR TITLE
DateBox: Fix native pickers showing if the drop-down button is clicked on a mobile device (T824701)

### PR DESCRIPTION
**Pull request by San4es**
**In 18.2:**

**In 19.1:**

**After this fix in 19.1:**
fix

### CODE REVIEW

**Comment by alexander-kotov-dx** [comment]
It breaks styles for the cases with custom buttons

**Review by alexander-kotov-dx — CHANGES_REQUESTED** [review]
It breaks styles for the cases with custom buttons

**Comment by San4es** [comment]
@alexander-kotov-dx Thank you!

**Comment by San4es** [comment]
@alexander-kotov-dx I have prepared an alternative fix (#10353). Please review it.

**Pull request closed without merging**
