### PR TITLE
Add new localization messages for v18.1

### PR DESCRIPTION
**Pull request by BingoRUS**
We're finishing features of the upcoming release v18.1 and now need some community help to localize new messages.

6 constants were added to localize [DataGrid/TreeList Filter Panel](https://github.com/DevExpress/DevExtreme/issues/3565):
1) dxDataGrid-filterBuilderPopupTitle (English equivalent: Filter Builder, [explanation](https://www.screencast.com/t/hyujuijL7))
2) dxDataGrid-filterPanelCreateFilter (English equivalent: Create Filter, [explanation](https://www.screencast.com/t/xvBgVvDE))
3) dxDataGrid-filterPanelClearFilter (English equivalent: Clear, [explanation](https://www.screencast.com/t/pfY4JRX2pU))
4) dxDataGrid-filterPanelFilterEnabledHint (English equivalent: Enable the filter, [explanation](https://www.screencast.com/t/LrfzDwLBTplc))
5) dxFilterBuilder-filterOperationAnyOf (English equivalent: Is any of, [explanation](https://www.screencast.com/t/eHLdgpj0dt))
6) dxFilterBuilder-filterOperationNoneOf (English equivalent: Is none of, [explanation](https://www.screencast.com/t/z18GQBkrST))

All these constants are temporary replaced with "!TODO" value for the following languages: [~Spanish~](https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/es.json), [~Finnish~](https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/fi.json), [~French~](https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/fr.json), [~Italian~](https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/it.json), [~Brazilian Portuguese~](https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/pt.json), [~Swedish~](https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/sv.json) and [~Chinese~](https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/zh.json).

Could you please help us with these localizations?
/cc @mrutter, @seek78, @beginor, @aenges, @Laupe, @jdvjdv82, @pedrofurtado, @perrich

Translations to ~German~ and ~Japanese~ are going to be added by DevExtreme team.

### CODE REVIEW

**Comment by aenges** [comment]
Hello Sergey

I usually don't use Github and is not interested in going through the whole pull-push session for a couple of rows, so here are the Swedish and Finnish translations for you to use.

Finnish:
-----------------------------------------------
"dxDataGrid-filterBuilderPopupTitle": "Suodattimen muodostin",
"dxDataGrid-filterPanelCreateFilterv": "Luo suodatin",
"dxDataGrid-filterPanelClearFilter": "Tyhjennä",
"dxDataGrid-filterPanelFilterEnabledHint": "Ota suodatin käyttöön",
"dxFilterBuilder-filterOperationAnyOf": "Joku näistä",
"dxFilterBuilder-filterOperationNoneOf": "Ei mikään näistä",

Swedish:
-----------------------------------------------
"dxDataGrid-filterBuilderPopupTitle": "Filterverktyg",
"dxDataGrid-filterPanelCreateFilter": "Skapa filter",
"dxDataGrid-filterPanelClearFilter": "Rensa",
"dxDataGrid-filterPanelFilterEnabledHint": "Aktivera filter",
"dxFilterBuilder-filterOperationAnyOf": "Någon av",
"dxFilterBuilder-filterOperationNoneOf": "Ingen av",

//anders

Från: Sergey Zvyagin <notifications@github.com>
Skickat: tisdag 24 april 2018 21:12
Till: DevExpress/DevExtreme <DevExtreme@noreply.github.com>
Kopia: Anders Enges (Borgast Ab) <anders@borgast.com>; Mention <mention@noreply.github.com>
Ämne: [DevExpress/DevExtreme] Add new localization messages for v18.1 (#3801)


We're finishing features of the upcoming release v18.1 and now need some community help to localize new messages.

6 constants were added to localize DataGrid/TreeList Filter Panel<https://github.com/DevExpress/DevExtreme/issues/3565>:

  1.  dxDataGrid-filterBuilderPopupTitle (English equivalent: Filter Builder, explanation<https://www.screencast.com/t/hyujuijL7>)
  2.  dxDataGrid-filterPanelCreateFilter (English equivalent: Create Filter, explanation<https://www.screencast.com/t/xvBgVvDE>)
  3.  dxDataGrid-filterPanelClearFilter (English equivalent: Clear, explanation<https://www.screencast.com/t/pfY4JRX2pU>)
  4.  dxDataGrid-filterPanelFilterEnabledHint (English equivalent: Enable the filter, explanation<https://www.screencast.com/t/LrfzDwLBTplc>)
  5.  dxFilterBuilder-filterOperationAnyOf (English equivalent: Any of, explanation<https://www.screencast.com/t/eHLdgpj0dt>)
  6.  dxFilterBuilder-filterOperationNoneOf (English equivalent: None of, explanation<https://www.screencast.com/t/z18GQBkrST>)

All these constants are temporary replaced with "!TODO" value for the following languages: Spanish<https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/es.json>, Finnish<https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/fi.json>, French<https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/fr.json>, Italian<https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/it.json>, Brazilian Portuguese<https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/pt.json>, Swedish<https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/sv.json> and Chinese<https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/zh.json>.

Could you please help us with these localizations?
/cc @mrutter<https://github.com/mrutter>, @seek78<https://github.com/seek78>, @beginor<https://github.com/beginor>, @aenges<https://github.com/aenges>, @Laupe<https://github.com/Laupe>, @jdvjdv82<https://github.com/jdvjdv82>, @pedrofurtado<https://github.com/pedrofurtado>, @perrich<https://github.com/perrich>

Translations to German and Japanese are going to be added by DevExtreme team.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/DevExpress/DevExtreme/pull/3801

Commit Summary

  *   Add new German messages for v18.1

File Changes

  *   M js/localization/messages/de.json<https://github.com/DevExpress/DevExtreme/pull/3801/files#diff-0> (12)

Patch Links:

  *   https://github.com/DevExpress/DevExtreme/pull/3801.patch
  *   https://github.com/DevExpress/DevExtreme/pull/3801.diff

**Comment by BingoRUS** [comment]
@aenges Big thanks! No worries, I pushed your changes.

**Comment by pedrofurtado** [comment]
@BingoRUS I've created a pull request with translations. That is the URL: https://github.com/BingoRUS/DevExtreme/pull/2

**Comment by perrich** [comment]
Hi, 

Please find french translation below :
        "dxDataGrid-filterBuilderPopupTitle": "Création de filtre",
        "dxDataGrid-filterPanelCreateFilter": "Créer un filtre",
        "dxDataGrid-filterPanelClearFilter": "Supprimer",
        "dxDataGrid-filterPanelFilterEnabledHint": "Activer le filtre",

        "dxFilterBuilder-filterOperationAnyOf": "Est parmi",
        "dxFilterBuilder-filterOperationNoneOf": "N'est pas parmi"

**Comment by BingoRUS** [comment]
@perrich Thank you! I pushed your changes.

**Comment by BingoRUS** [comment]
@pedrofurtado I merged your PR and now your changes appear here. As the contributor of Spanish translation, could you please add new translated messages [to this file](https://github.com/DevExpress/DevExtreme/blob/18_1/js/localization/messages/es.json) too?

**Comment by marcellorutter** [comment]
@BingoRUS just created a PR to your fork i18_181.

**Comment by BingoRUS** [comment]
@mrutter Thank you, merged your changes.

**Comment by pedrofurtado** [comment]
@BingoRUS Ok, I will translate the spanish. I will open another pull request for this.

**Comment by pedrofurtado** [comment]
@BingoRUS Pull request created for Spanish translations. Here is the URL: https://github.com/BingoRUS/DevExtreme/pull/4

**Comment by BingoRUS** [comment]
@pedrofurtado Thanks, I approved your PR.

**Comment by BingoRUS** [comment]
@beginor I moved your changes here. Thank you for the contribution!

**Review by sometimesElen — APPROVED** [review]

**Comment by jdvjdv82** [comment]
Czech:
-----------------------------------------------
"dxDataGrid-filterBuilderPopupTitle": "Tvorba Filtru",
"dxDataGrid-filterPanelCreateFilterv": "Vytvořit Filtr",
"dxDataGrid-filterPanelClearFilter": "Smazat",
"dxDataGrid-filterPanelFilterEnabledHint": "Povolit Filtr",
"dxFilterBuilder-filterOperationAnyOf": "Libovolný z",
"dxFilterBuilder-filterOperationNoneOf": "Žádný z",

**Comment by BingoRUS** [comment]
@jdvjdv82 I've merged your translation in [another pull request](https://github.com/DevExpress/DevExtreme/pull/3902). Thank you for cooperation.

**Pull request merged**
