### PR TITLE
Remove deprecated in 16.1 dxExporter

### PR DESCRIPTION
**Pull request by alexanderPolosatov**
@lukyanovas 
1. Do we need to update legacy TS definitions (done in the context of this PR)?
2. Do we need to update actual TS definitions in the context of this PR?

/cc @dxbykov

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
@alexey-semikozov 🔥 🙌 🎆

**Review by AlekseyMartynov — COMMENTED** [review]
🖤

**Review by lukyanovas — APPROVED** [review]
@alexanderPolosatov 
1. We want to remove all legacy ts in 18.2. If you've already removed exporter parts - it's ok.
2. I'll update all ts declarations at the end of the week.

**Review by alexey-semikozov — APPROVED** [review]
🎉 🎉 🎉

**Pull request merged**
