### PR TITLE
Fixes in localization messages for 'it' locale

### PR DESCRIPTION
**Pull request by marcellorutter**
Fixed minor grammar errors
Fixed minor inconsistencies
Fixed some inaccuracies
See also ticket T311368

### CODE REVIEW

**Comment by BingoRUS** [comment]
@seek78 As an initial contributor of Italian messages, could you please take a look at these changes?
@mrutter Could you please rollback the formatting changes? We usually use spaces in our source code, not tabs.

**Comment by marcellorutter** [comment]
@BingoRUS I just pushed the new version without tabs. Thanks.

**Review by marcellorutter — COMMENTED** [review]
@BingoRUS Please forgive, I didn't noticed the extra spaces at the beginning. Thank you.

**Comment by BingoRUS** [comment]
@mrutter No worries, I just want to make sure [the diff](https://github.com/DevExpress/DevExtreme/pull/3207/files) shows changes only in messages. It's simpler to review.
Anyway, I'm not able to check your corrections because I don't speak Italian. So let's wait for the initial contributor comments (or any other native speakers from the community). I hope we will be ready to merge this PR until the next minor release. Thanks.

**Comment by marcellorutter** [comment]
@BingoRUS Ok, thank you. Please note that I'm italian (thus I'm a native speaker); also I contributed to translate messages in the past (through DevExpress Support Center). Anyway, no problem to wait the initial contributor even because currently I'm deploying the localization to my customers by myself (copying the file to node_modules/devextreme/...). Thanks.

**Comment by BingoRUS** [comment]
@seek78 could you review the changes in this PR?

**Review by seek78 — APPROVED** [review]

**Review by seek78 — APPROVED** [review]

**Review by BingoRUS — APPROVED** [review]

**Pull request merged**
