### PR TITLE
Implement callOnce utility

### PR DESCRIPTION
**Pull request by nightskylark**

### CODE REVIEW

**Review by ovchinnikov — APPROVED** [review]

**Comment by San4es** [comment]
@nightskylark 

It looks like we can simplify the `callOnce` utility implementation to:

```
var callOnce = function(handler) {
    var result;

    return function() {
        result = handler.apply(this, arguments);
        handler = function() {
            return result;
        };
        return result;
    };
};
```

or

```
var callOnce = function(handler) {
    var result, called;

    return function() {
        if(!called) {
            result = handler.apply(this, arguments);
            called = true;
        }        
        return result;
    };
};

**Comment by nightskylark** [comment]
@San4es Condition check has lower performance https://jsperf.com/empty-vs-check

**Comment by San4es** [comment]
@nightskylark 

Ok. What about the first option?

**Comment by nightskylark** [comment]
Oh. I thought that was mine :)
In this case, we will reassign `handler` variable on each method call. I have decided that it's better to have more complex but more logical code.

**Comment by San4es** [comment]
@nightskylark 

In your implementation, we create +1 unnecessary closure and +1 `.apply(this, arguments);` call. What jsPerf says about this case? :)

@ovchinnikov What do you think?

**Comment by ovchinnikov** [comment]
I think that only browsers know what implementation is better. So if you want to know what implementation is faster you should create an example and compare execution time.

**Comment by San4es** [comment]
@ovchinnikov @nightskylark 

Both variants are almost identical in performance (the second is a little faster):
https://jsfiddle.net/Lupavwwr/

But I think that the second one has a simpler and more clear code to me.

**Pull request merged**
