### PR TITLE
Remove doT dependency

### PR DESCRIPTION
**Pull request by San4es**
Motivation:
https://github.com/DevExpress/DevExtreme/network/alerts
https://hackerone.com/reports/390929

### CODE REVIEW

**Comment by nightskylark** [comment]
@San4es  This is a `devDependency` and it's used only for testing. I can't see how this vulnerability could affect in this case. And I don't think we should test unstable version because of it.

**Comment by San4es** [comment]
We have a private discussion with @nightskylark. His suggestion is to remove the "doT" dependency and tests for it.

**Review by vconst — DISMISSED** [review]

**Comment by San4es** [comment]
@nightskylark @vconst thank you for your feedback!
I am going to merge this PR. We can separate third-party template engines integrations and move them to demos level in future major releases.

**Comment by nightskylark** [comment]
I still think that using beta-version of dependency is a hack solution that is not needed.

**Comment by nightskylark** [comment]
Also, as I can see, the `dot` v 2.0 uses `new Function` too.
https://github.com/olado/doT/blob/v2.0.0/doT.js#L69
https://github.com/olado/doT/blob/v2.0.0/doT.js#L83
https://github.com/olado/doT/blob/v2.0.0/doT.js#L133

**Review by nightskylark — APPROVED** [review]

**Comment by San4es** [comment]
@nightskylark Oh, thank you!

>His suggestion is to remove the "doT" dependency and tests for it.

you win! :wink:

**Pull request merged**
