### PR TITLE
Mark Panorama and Pivot widgets as deprecated

### PR DESCRIPTION
**Pull request by San4es**
**Suggested recommendations for replacement:**
Pivot -> TabPanel
Panorama -> TabPanel, MultiView

### CODE REVIEW

**Review by BingoRUS — APPROVED** [review]
👌

**Review by TikhonovaTatyana — APPROVED** [review]
What to do with guides on deprecated widgets? Delete or leave with a note?

**Comment by San4es** [comment]
>What to do with guides on deprecated widgets? Delete or leave with a note?

I vote for "leave with a note".

**Comment by BingoRUS** [comment]
I vote for “delete”

________________________________

**Review by lukyanovas — APPROVED** [review]

**Review by dxbykov — APPROVED** [review]

**Review by NickMitrokhin — APPROVED** [review]

**Pull request merged**
