### PR TITLE
Add sankey to WidgetsCreation.tests

### PR DESCRIPTION
**Pull request by alexanderPolosatov**

### CODE REVIEW

**Review by roman-simionov — APPROVED** [review]

**Comment by roman-simionov** [comment]
@romanresh @kruglikovstepan @groshenkovamarina  @nightskylark 
What about Diagram, File manager, SpeedDialAction?
I have noticed that they are missed in the widgets list.

**Comment by nightskylark** [comment]
I was talking with @kruglikovstepan, and he was going to add the Gantt Diagram here. As for the rest of these widgets, ofcourse it should be added to before publising as a stable API. I suppose we should automate it somehow in future.

**Comment by kruglikovstepan** [comment]
In 19.2 the gantt has already been added
https://github.com/alexanderPolosatov/DevExtreme/blob/19_2/testing/tests/DevExpress.serverSide/widgetsCreation.tests.js

What about File manager - cc to: @maxerokh @vladkovl

**Comment by vladkovl** [comment]
FileManager should be added in 19_2 version in the context of [this PR](https://github.com/DevExpress/DevExtreme/pull/9358/files).
Do we need to add this widget to the widgets list in 19_1 version too?

**Comment by roman-simionov** [comment]
> Do we need to add this widget to the widgets list in 19_1 version too?

yes, since it is added in v19.1
https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFileManager/

**Pull request merged**
