### PR TITLE
Add capability to split widget rendering into two parts

### PR DESCRIPTION
**Pull request by ovchinnikov**
Widget rendering was split into two parts:
1) _initMarkup() - first part of widget rendering. You can't get elements sizes here. It's possible to create elements and set classes only.
2) _render() - Second part of rendering. It's possible to use DOM sizes and other browsers API.

### CODE REVIEW

**Review by nightskylark — DISMISSED** [review]

**Review by mrjohn0011 — DISMISSED** [review]

**Review by vconst — COMMENTED** [review]
I think that the _mount and the _isReadyToMount methods are unnecessary. There are no scenarios to override and call them directly. So, it will be better to inline them to _renderComponent:

```javascript
    _renderComponent: function() {
        this._initMarkup();
        if(windowUtils.hasWindow()) {
            this._render();
        }
    }
```

Please do not use "mount" in these method names because current server-side API is not compatible with react/vue.

**Comment by ovchinnikov** [comment]
@vconst We have scenarios where we should check capability to use browsers API (for example all charts get elements width/height on init state of widget). So it's better to have one method to detect this capability.

Is "mount" reserved word by React/Vue? Why we can't use this word?

**Review by dxvladislavvolkov — DISMISSED** [review]

**Comment by vconst** [comment]
@ovchinnikov
- It is not logical to check the capability to use browsers API by method _isReadyToMount. Also if all charts get elements width / height on init state of a widget, that this code should be moved to _render and _isReadyToMount will be not necessary. Also, it is more logical name is _isServer or such another.

- It is not a logical check ready to mount in the _mount method. If you are ready to mount call _render is not logical.

- If we add another server-side API for react / vue the "mount" name may be used in such API. But in this PR it is reserved for angular server-side internal methods.

The method "_mount" can not be called directly and there is no sense to overload it. All widgets will implement _initMarkup and _render methods. Why we add new work / phase "_mount" if it is not necessary and it is not used in our widgets directly?

**Comment by ovchinnikov** [comment]
@vconst  
Are you sure that it's possible to move rendering part for charts widgets? Why should we do this although we know that charts will not render on a server at all?

Anyway, as you wish...

**Review by vconst — APPROVED** [review]

**Pull request merged**
