### PR TITLE
Use same quotes style for the entire project

### PR DESCRIPTION
**Pull request by nightskylark**

### CODE REVIEW

**Review by ovchinnikov — DISMISSED** [review]

**Comment by churkin** [comment]
Great work!

**Review by churkin — DISMISSED** [review]

**Review by vconst — COMMENTED** [review]
Cherry pick it to 19_2

**Review by jsdmitry — DISMISSED** [review]

**Review by San4es — DISMISSED** [review]
Consistency is good, but I vote for double quotes.

**Review by pavelgruba — DISMISSED** [review]

**Comment by nightskylark** [comment]
> Cherry pick it to 19_2

@vconst , now you got this https://github.com/DevExpress/DevExtreme/pull/11145

**Review by vconst — APPROVED** [review]

**Pull request merged**
