### PR TITLE
Fix for-loops over arrays

### PR DESCRIPTION
**Pull request by AlekseyMartynov**
Found by a user in https://devexpress.com/issue=T695223

I spotted incorrect loops by running tests with 
- [Instumented code base](https://github.com/DevExpress/DevExtreme/commit/1525ab19f0b2f015e681e199160a3436858ffc68)
- [Intentionally polluted `Array.prototype`](https://github.com/DevExpress/DevExtreme/commit/70735b54a7c1f7e7384a449a3bf1c103bdeb71ae)

---

What do you think about adding this to our QUnit test page to prevent future errors?
https://github.com/DevExpress/DevExtreme/blob/70735b54a7c1f7e7384a449a3bf1c103bdeb71ae/testing/runner/Views/Main/RunSuite.cshtml#L47

### CODE REVIEW

**Comment by nightskylark** [comment]
Why don't use `eslint` rule [guard-for-in](https://eslint.org/docs/rules/guard-for-in)?

**Comment by AlekseyMartynov** [comment]
@nightskylark 
With `guard-for-in`, we'll need to check & fix approx. 80 more loops.
Here I change specifically `for-in`'s over arrays, for which changing loop type is better than adding `hasOwnProperty`.

**Comment by San4es** [comment]
>What do you think about adding this to our QUnit test page to prevent future errors?

👍

**Comment by San4es** [comment]
What about this case?
https://github.com/DevExpress/DevExtreme/blob/18_2/js/core/utils/extend.js#L34

**Comment by AlekseyMartynov** [comment]
@San4es 
> What about this case?

Would you ask a more specific question about this case?

**Comment by San4es** [comment]
Do we need to handle a case when `source` is Array and use `for...of` for it instead of `for...in`?

**Comment by AlekseyMartynov** [comment]
@San4es 

I don't know.
Let's discuss it separately? 🤔

This PR is more specific. I'm only changing the loops for which it's clear that the collection is _always_ an array. I'm solving a practical problem (ticket T695223).

**Review by ovchinnikov — APPROVED** [review]

**Review by San4es — APPROVED** [review]

**Review by lukyanovas — APPROVED** [review]

**Pull request merged**
