### PR TITLE
Add localization messages for 'fr' locale

### PR DESCRIPTION
**Pull request by BingoRUS**
@perrich
I'm cherry-picking French localization messages to recently released 17.2 version. Some new constants were added:
- dxScheduler-moreAppointments
- dxTagBox-selected
- dxTagBox-allSelected
- dxTagBox-moreSelected
- dxFilterBuilder-and
- dxFilterBuilder-or
- dxFilterBuilder-notAnd
- dxFilterBuilder-notOr
- dxFilterBuilder-addCondition
- dxFilterBuilder-addGroup
- dxFilterBuilder-enterValueText
- dxFilterBuilder-filterOperationEquals
- dxFilterBuilder-filterOperationNotEquals
- dxFilterBuilder-filterOperationLess
- dxFilterBuilder-filterOperationLessOrEquals
- dxFilterBuilder-filterOperationGreater
- dxFilterBuilder-filterOperationGreaterOrEquals
- dxFilterBuilder-filterOperationStartsWith
- dxFilterBuilder-filterOperationContains
- dxFilterBuilder-filterOperationNotContains
- dxFilterBuilder-filterOperationEndsWith
- dxFilterBuilder-filterOperationIsBlank
- dxFilterBuilder-filterOperationIsNotBlank

Could you please help us with the translations there? Original English messages can be found [here](https://github.com/DevExpress/DevExtreme/blob/17_2/js/localization/messages/en.json).
I gave you permissions to my fork so you can push the changes directly to this pull request. Or just leave your comments here.

### CODE REVIEW

**Comment by perrich** [comment]
Ok, I'll check that.

**Comment by perrich** [comment]
Sorry, I don't know how to get the PR and commit to it.

The translation is:
        "dxScheduler-moreAppointments": "{0} en plus",
        "dxTagBox-selected": "{0} selectionnés",
        "dxTagBox-allSelected": "Tous sélectionnés ({0})",
        "dxTagBox-moreSelected": "{0} en plus",
        "dxFilterBuilder-and": "Et",
        "dxFilterBuilder-or": "Ou",
        "dxFilterBuilder-notAnd": "Non Et",
        "dxFilterBuilder-notOr": "Non Ou",
        "dxFilterBuilder-addCondition": "Ajouter une condition",
        "dxFilterBuilder-addGroup": "Ajouter un groupe",
        "dxFilterBuilder-enterValueText": "<entrer une valeur>",
        "dxFilterBuilder-filterOperationEquals": "Est égal à",
        "dxFilterBuilder-filterOperationNotEquals": "Est différent de",
        "dxFilterBuilder-filterOperationLess": "Est plus petit que",
        "dxFilterBuilder-filterOperationLessOrEquals": "Est plus petit ou égal à",
        "dxFilterBuilder-filterOperationGreater": "Est plus grand que",
        "dxFilterBuilder-filterOperationGreaterOrEquals": "Est plus grand ou égal à",
        "dxFilterBuilder-filterOperationStartsWith": "Commence par",
        "dxFilterBuilder-filterOperationContains": "Contient",
        "dxFilterBuilder-filterOperationNotContains": "Ne contient pas",
        "dxFilterBuilder-filterOperationEndsWith": "Finit par",
        "dxFilterBuilder-filterOperationIsBlank": "Est vide",
        "dxFilterBuilder-filterOperationIsNotBlank": "N'est pas vide"

**Comment by BingoRUS** [comment]
My fault, I didn't give you exact links. It was possible to add commits by pushing to the [i18n_fr_172](https://github.com/BingoRUS/DevExtreme/tree/i18n_fr_172) branch on [BingoRUS/DevExtreme](https://github.com/BingoRUS/DevExtreme). GitHub shows a note somewhere in this conversation. Or to [edit the file from the browser](https://github.com/BingoRUS/DevExtreme/edit/i18n_fr_172/js/localization/messages/fr.json?pr=/DevExpress/DevExtreme/pull/2964) by pressing the button with pencil icon on [Files changed](https://github.com/DevExpress/DevExtreme/pull/2964/files) tab.

But it's not a problem, I will add these strings now. @perrich, by the way, what is the translation for "dxFilterBuilder-enterValueText" constant?

**Comment by perrich** [comment]
I've not the right to edit (pencil icon is disabled).
"dxFilterBuilder-enterValueText": "<entrer une valeur>",

**Comment by BingoRUS** [comment]
@perrich you need to [accept the invitation](https://github.com/BingoRUS/DevExtreme/invitations) first.
Is there just an empty constant? Can we use a translation of "&lt;enter a value&gt;"?

UPD: I see the problem now. GitHub doesn't escape symbols, thinks it's a tag and shows nothing... Write a string without &lt; and &gt; please.

**Comment by perrich** [comment]
It works and the file is now fixed (sorry for the HTML tag issue...).

**Comment by BingoRUS** [comment]
@perrich Thank you so much! We will merge this PR shortly and the localization will be available with the next minor release of DevExtreme.

**Review by San4es — APPROVED** [review]

**Pull request merged**
