### PR TITLE
Remove custom theme builder, simplify TB meta

### PR DESCRIPTION
**Pull request by babich-a**
Removed
- custom theme generator ('custom-theme' command for style-compiler)
- generation of legacy generic styles
- extra parameters from the themebuilder metadata

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
We use the `custom-theme` command in `Packer.cmd` for DevAV and GolfClub demos.

**Comment by babich-a** [comment]
> 
> 
> We use the `custom-theme` command in `Packer.cmd` for DevAV and GolfClub demos.

I have already changed `style-compiler custom-theme` to `devextreme build-theme`

**Review by AlekseyMartynov — APPROVED** [review]
LGTM

**Review by BingoRUS — APPROVED** [review]
👌

**Pull request merged**
