### PR TITLE
Get the version from package.json only (#6871)

### PR DESCRIPTION
**Pull request by babich-a**

### CODE REVIEW

**Review by San4es — DISMISSED** [review]
LGTM

**Review by BingoRUS — DISMISSED** [review]

**Comment by babich-a** [comment]
This approach does not work with "gulp dev". I think we need to try something like webpack.DefinePlugin if we can.

**Comment by babich-a** [comment]
I have fixed the `gulp dev` task by https://github.com/DevExpress/DevExtreme/pull/7020/commits/ad4ee491b476c43cfea4dc85dd792f774d43e1ea We can't use this approach for the `npm run build` because webpack is not used for scripts that we put to the npm package.

**Review by BingoRUS — APPROVED** [review]
👌

**Pull request merged**
