### PR TITLE
Resolves T211239

### PR DESCRIPTION
**Pull request by Seteh**

### CODE REVIEW

**Review by AlekseyMartynov — APPROVED** [review]

**Review by vconst — APPROVED** [review]

**Review by San4es — APPROVED** [review]
LGTM

**Review by dxvladislavvolkov — APPROVED** [review]

**Comment by Seteh** [comment]
Thanks to all.

**Comment by IgnatovDan** [comment]
http://jsben.ch/zbkTf - '_if(time[4])_' seems to be 10% faster than '_(time[4] || "")_'

**Comment by IgnatovDan** [comment]
http://jsben.ch/eUEie or https://jsperf.com/formatiso8601-plus-vs-or/1 - '_date.getHours() || date.getMinutes() || date.getSeconds() || date.getMilliseconds()_' seems to be 30% faster than '_date.getHours() + date.getMinutes() + date.getSeconds() + date.getMilliseconds() < 1_' for full date values like '_new Date(2019, 0, 15, 1, 2, 3, 123))_'

**Comment by IgnatovDan** [comment]
http://jsben.ch/GkmS2 or https://jsperf.com/formatiso8601-plus-vs-or/1 - and 30% difference for date values without _milliseconds_ like 'new Date(2019, 0, 15, 1, 2, 3, 0))'

**Comment by IgnatovDan** [comment]
http://jsben.ch/jAr66 or https://jsperf.com/formatiso8601-array-join-vs-string-plus/1 - '_string + string_' seems to be 30% faster than '_array.join_'

**Comment by IgnatovDan** [comment]
http://jsben.ch/FSmlX or https://jsperf.com/formatiso8601-array-join-vs-string-plus/1 - '_string + string_' seems to be 30% faster than '_array.join_'

**Comment by AlekseyMartynov** [comment]
Cool. How about another PR focused on perf optimization?

**Comment by Seteh** [comment]
@IgnatovDan could you please provide us with the results on the minified code bundle as well?

**Pull request merged**
