### PR TITLE
TagBox - Fix double item loading on initialization (T533200)

### PR DESCRIPTION
**Pull request by San4es**

### CODE REVIEW

**Comment by mrjohn0011** [comment]
I think there is a better way to fix this issue than inserting a flag. It will better to research on it

**Comment by San4es** [comment]
@mrjohn0011 
I agree with you that it may be fixed without a flag. I spent some time researching alternative fixes, but they affect TagBox parent classes (SelectBox, DropDownList, etc) implementations more widely. This fix is minimal in terms of possible side effects. Do you have any specific ideas for improving this fix?

@vconst @lukyanovas 
Please, share your thoughts with us.

**Comment by lukyanovas** [comment]
@San4es I think you can create a method ('_loadInputValue' or something like this) in the base 'DropDownList' class and override it in the TagBox. It will be more clear and logic of the 'DropDownList' will not be corrupted.

**Review by mrjohn0011 — APPROVED** [review]

**Comment by San4es** [comment]
@lukyanovas 
Thank you for this direction! I refactored my fix according to it.

@mrjohn0011 @vconst 
Take a look at it now, please.

**Review by vconst — APPROVED** [review]

**Review by lukyanovas — APPROVED** [review]

**Pull request merged**
