### PR TITLE
Show error when searching or filtering an Int32 field in ODataStore

### PR DESCRIPTION
**Pull request by dxvladislavvolkov**

### CODE REVIEW

**Review by nightskylark — COMMENTED** [review]
LGTM

**Comment by AlekseyMartynov** [comment]
1. The check is not specific to `Int32`
   ```js
   isStringFunction(criteria[1]) && fieldTypes[criteria[0]] !== 'String'
   ```
   A better error message would be:
   ```
   String function X cannot be used with the data field Y of type Z.
   ```
   @RomanTsukanov can help with the message.

2. Perhaps `isEmptyObject` is an overkill:
   ```js
   !typeUtils.isEmptyObject(fieldTypes)
   ```
   Guard should be sufficient: `fieldTypes && fieldTypes[...] !== ...`  
   Or even `fieldTypes?[...]` - refer to https://github.com/DevExpress/DevExtreme/pull/11291.

**Comment by AlekseyMartynov** [comment]
Парни, давайте резать оливье и заправлять шубу!

**Comment by RomanTsukanov** [comment]
> String function X cannot be used with the data field Y of type Z.

This one is suitable.

**Review by AlekseyMartynov — APPROVED** [review]

**Pull request merged**
