### PR TITLE
Fix itemTitleTemplate option in dxAccordion for material theme

### LINKED ISSUE #4022: Accordion panel is missing titles when Material theme is used
### Steps to Reproduce:

1. Go to DevExpress demos
2. Select Navigation -> Accordion
3. Select Material design theme

### Results You Received:
Accordion titles are not visible

### Results You Expected:
Accordion titles are visible

### Environment Details:
Chrome 66
DevExtreme Angular 18.1

### PR DESCRIPTION
**Pull request by groshenkovamarina**
Fixed #4022

### CODE REVIEW

**Comment by DokaRus** [comment]
Is there a public issue or an SC ticket that related to this PR? 
Can you add a test?

**Comment by DokaRus** [comment]
Maybe we can use the same markup (like for Material) for all themes and remove `themes.isMaterial()` ternary operator?

**Review by mrjohn0011 — DISMISSED** [review]
LGTM

**Comment by groshenkovamarina** [comment]
@DokaRus yes. there is [issue](https://github.com/DevExpress/DevExtreme/issues/4022). We have the test already.

**Comment by groshenkovamarina** [comment]
@DokaRus let's try, done for all themes

**Review by mrjohn0011 — APPROVED** [review]

**Pull request merged**
