### PR TITLE
Remove dx.spa.css 

### PR DESCRIPTION
**Pull request by KonyukhovSergey**
This PR removes the 'dx.spa.css'. Since we had [removed the SPA framework](https://github.com/DevExpress/DevExtreme/pull/7185) this file contains only CSS reset styles. We had decided to remove it by the following reasons:
 * This CSS covers only DevExtreme SPA framework requirements
 * DevExtreme is a controls library and should not change an application environment
 * The 'dx.(reset|spa).css' itself is not very useful without other layout tools
 * There are third-party CSS reset styles: [Reboot, Resets, and Reasoning](https://css-tricks.com/reboot-resets-reasoning/).

### CODE REVIEW

**Review by AlekseyMartynov — APPROVED** [review]

**Review by BingoRUS — APPROVED** [review]

**Comment by San4es** [comment]
@jauseg  Did we remove all 'dx.spa.css' occurrences in demos, tools and other places in our main repo?

**Comment by San4es** [comment]
@dxbykov any thoughts?

**Comment by KonyukhovSergey** [comment]
@San4es yes, We have removed all 'dx.spa.css' occurrences.

**Review by San4es — APPROVED** [review]
LGTM

**Pull request merged**
