### PR TITLE
CI - Add TS task

### PR DESCRIPTION
**Pull request by San4es**
To ensure that all TS build tasks are succeeded.

**Case:**
The #6727 PR was merged with compilation errors in TS.

### CODE REVIEW

**Review by pavelgruba — DISMISSED** [review]

**Review by AlekseyMartynov — COMMENTED** [review]
I don't like it.
Is it possible to have a specific small TypeScript checking task instead?

**Comment by AlekseyMartynov** [comment]
Additional consideration:
`npm run build` & `gulp build` will have the same name but different meaning.

**Comment by San4es** [comment]
Yes,

>Is it possible to have a specific small TypeScript checking task instead?

https://devextreme-ci.devexpress.com/DevExpress/DevExtreme/12454/18

**Comment by AlekseyMartynov** [comment]
@San4es Cool

@nightskylark @ovchinnikov We noticed an issue with the related Gulp tasks.
`ts-sources` and `npm-dts-generator` are executed twice (see [build logs](https://devextreme-ci.devexpress.com/DevExpress/DevExtreme/12454/18)). Likely due to the mix of dependent tasks and `runSequence`. How can we break this knot?

**Comment by nightskylark** [comment]
@AlekseyMartynov  How about such a solution?
https://github.com/DevExpress/DevExtreme/pull/6772

**Comment by AlekseyMartynov** [comment]
@nightskylark 

Гениально!

**Comment by San4es** [comment]
From https://devextreme-ci.devexpress.com/DevExpress/DevExtreme/12495/18:

```
[12:12:10] Using gulpfile /drone/src/github.com/DevExpress/DevExtreme/gulpfile.js
[12:12:10] Starting 'ts-vendor'...
[12:12:10] Starting 'ts-sources'...
[12:12:10] Finished 'ts-vendor' after 37 ms
[12:12:10] Finished 'ts-sources' after 84 ms
[12:12:10] Starting 'ts-check'...
[12:12:15] Finished 'ts-check' after 4.76 s
[12:12:15] Starting 'ts'...
[12:12:15] Finished 'ts' after 24 μs
Using QUnit CI mode for gulp default!
[12:12:16] Using gulpfile /drone/src/github.com/DevExpress/DevExtreme/gulpfile.js
[12:12:16] Starting 'npm-dts-generator'...
[12:12:17] Finished 'npm-dts-generator' after 225 ms
[12:12:17] Starting 'npm-sources'...
[12:12:17] Starting 'npm-dts-check'...
[12:12:22] Finished 'npm-dts-check' after 5.44 s
[12:12:22] Starting 'npm-check'...
[12:12:22] Finished 'npm-check' after 156 μs
[12:12:22] Finished 'npm-sources' after 5.7 s
[12:12:22] Starting 'npm'...
[12:12:22] Finished 'npm' after 6.07 μs
```

**Comment by nightskylark** [comment]
@San4es 5 seconds :)

**Review by AlekseyMartynov — APPROVED** [review]

**Review by pavelgruba — APPROVED** [review]

**Review by BingoRUS — APPROVED** [review]
👍

**Pull request merged**
